### ISSUE TITLE
Handling of indirect descriptor violates virtio spec

### ISSUE THREAD

**Issue by jiangliu** [rust-vmm/vm-virtio#28]
According to Virtio spec 1.1, 2.6.5.3.2 Device Requirements: Indirect Descriptors:
_The device MUST ignore the write-only flag (flags&VIRTQ_DESC_F_WRITE) in the descriptor that refers
to an indirect table.
The device MUST handle the case of zero or more normal chained descriptors followed by a single descriptor
with flags&VIRTQ_DESC_F_INDIRECT
Note: While unusual (most implementations either create a chain solely using non-indirect descriptors, or
use a single indirect element), such a layout is valid._

And commit "a83152da14554cf810f672f6f4079e943fe6ce28 : simplify descriptor chain handling" breaks the rules defined above.

**Comment by jiangliu** [comment]
DescriptorChain::process_indirect_descriptor() modifies the several fields of the DescriptorChain object according to the indirect descriptor, and it won't be restored when we reach the end of the indirect chain. So all descriptors after the indirect descriptor on the main chain will be ignored.

**Comment by alexandruag** [comment]
Hmm, as far as I understand, there can be no descriptors after the indirect chain. The implementation in a83152da14 follows the provision quoted above as follows:

- Regular descriptors are parsed until an indirect descriptor is found.
- If that ever happens, `process_indirect_descriptor` is used to essentially jump to the indirect descriptor table.

Thus, we support any number of normal chained descriptors followed by a single indirect descriptor. We don't support returning to the original chain, but that's not necessary because (according to 2.6.5.3.1) *a driver MUST NOT set both VIRTQ_DESC_F_INDIRECT and VIRTQ_DESC_F_NEXT in flags*, so there can be no other descriptors after the first indirect descriptor. Moreover, we don't support nested indirect descriptor tables, but that's also not required because (according to  the same section) *the driver MUST NOT set the VIRTQ_DESC_F_INDIRECT flag within an indirect descriptor (ie. only one table per descriptor)*. Does this sound reasonable?

**Comment by jiangliu** [comment]
With more investigation, the Virtio PCI Card Specication v0.9.5 DRAFT, 2.3.3 Indirect Descriptors:
_The rst indirect descriptor is located at start of the indirect descriptor table (index 0), additional indirect descriptors are chained by next eld. An indirect descriptor without next eld (with ags&NEXT o) signals the end of the indirect descriptor table, and transfers control back to the main virtqueue. An indirect descriptor can not refer to another indirect descriptor table (ags&INDIRECT must be o)._ 
And there's no definition about "the driver MUST NOT set the VIRTQ_DESC_F_INDIRECT flag within an indirect descriptor (ie. only one table per descriptor)".

Starting from virtio spec 1.0, there's clear definition of "the driver MUST NOT set the VIRTQ_DESC_F_INDIRECT flag within an indirect descriptor (ie. only one table per descriptor)".

So current implementation confirms to virtio spec 1.0/1.1, but may violates 0.95.

**Comment by bonzini** [comment]
There is: "An indirect descriptor can not refer to another indirect descriptor table (flags&INDIRECT must be off)."

**Comment by alexandruag** [comment]
Thanks for clearing that up Gerry, I wasn't aware of this particular difference vs older versions of the standard. I think that only supporting 1.0 and later is preferable, because there are a lot of extra corner cases to consider if we want to add legacy compatibility as well. Does that sound reasonable?

**Comment by jiangliu** [comment]
> Thanks for clearing that up Gerry, I wasn't aware of this particular difference vs older versions of the standard. I think that only supporting 1.0 and later is preferable, because there are a lot of extra corner cases to consider if we want to add legacy compatibility as well. Does that sound reasonable?

Sure, then a comment is welcomed!

**Comment by alexandruag** [comment]
Cool, I've made a note to add a comment the next time I post a change or PR.
