### ISSUE TITLE
Publish vm-virtio to crates.io

### ISSUE THREAD

**Issue by jiangliu** [rust-vmm/vm-virtio#40]
There are several projects depend on the vm-virtio crate, so it's desired to publish the vm-virtio early.

**Comment by alexandruag** [comment]
Looks like a good first step is to reach a conclusion for each ongoing PR (and maybe #42), and then we can follow up with the usual pre-publishing steps.

**Comment by slp** [comment]
@jiangliu @andreeaflorescu Now that this repository contains a workspace with multiple crates, can we publish each one of them independently?

There are many projects depending on `virtio-queue`, so it'd be really nice getting it into crates.io.

**Comment by jiangliu** [comment]
Indeed, several other crates have been blocked by virtio-queue for a while now.
We should publish virtio-queue independently. But I have some pending PR for virtio-queue, will send it out soon.

**Comment by andreeaflorescu** [comment]
I think there were some concerns related to the interface that we needed to address first. We should also do an evaluation of the crate to see what else is needed for publishing to crates.io.

It looks like the documentation is a bit behind, and will need some improvements. On the testing side, we should check if there are any improvements areas.

It would help to evaluate the crate and come up with a list of tasks (similar to what we've done for vm-fdt here: https://github.com/rust-vmm/vm-fdt/issues/8) so it is easier to track where we are, and what needs to happen before we can publish it. Do we use this issue as the parent?

What would be a good idea I think is to try to align the implementations in consuming products (Firecracker, Cloud Hypervisor, Alibaba's VMM), so that we avoid breaking changes once we publish it if that is possible.

**Comment by jiangliu** [comment]
> I think there were some concerns related to the interface that we needed to address first. We should also do an evaluation of the crate to see what else is needed for publishing to crates.io.
> 
> It looks like the documentation is a bit behind, and will need some improvements. On the testing side, we should check if there are any improvements areas.
> 
> It would help to evaluate the crate and come up with a list of tasks (similar to what we've done for vm-fdt here: [rust-vmm/vm-fdt#8](https://github.com/rust-vmm/vm-fdt/issues/8)) so it is easier to track where we are, and what needs to happen before we can publish it. Do we use this issue as the parent?
> 
> What would be a good idea I think is to try to align the implementations in consuming products (Firecracker, Cloud Hypervisor, Alibaba's VMM), so that we avoid breaking changes once we publish it if that is possible.

Yes, my pending PR is to support smooth transition of the existing consumers of virtio-queue crate.

**Comment by andreeaflorescu** [comment]
Task Breakdown:
- [ ] https://github.com/rust-vmm/vm-virtio/issues/87
- [ ] TODO

**Comment by jiangliu** [comment]
Almost one year past, and we are eventually near to publish v0.1.0:)

**Comment by lauralt** [comment]
virtio-queue is published. For the other crates of vm-virtio, we can open separate issues for tracking their publishing.
