### ISSUE TITLE
 Design a mocking framework for virtio queues

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vm-virtio#62]
As part of this task we want to define what & how we want to implement the mocking framework. The delivery of this task is a design document that can be used to further break down #61.

**Comment by krady21** [comment]
Instead of writing a mock framework from scratch, we decided to add two helper functions:
* The first one would allow us to more easily create descriptor chains by adding a new structure called `MockDescriptor. This struct would provide users with a way to incrementally create descriptors, similar to how a builder pattern works.
* The second one would allow us to write a buffer ([u8]) to the underlying memory regions that a chain of descriptors point to.
